import{a as p,S as w,i as m}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="43780784-35e4285ec8f2021d0fe97b31d",P="https://pixabay.com/api/";p.defaults.baseURL=P;const f=15,g=async(r="photo",t)=>{const o={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f};return p.get("",{params:{...o}})},y=r=>r.map(({largeImageURL:t,webformatURL:o,tags:l,likes:e,views:s,comments:a,downloads:E})=>`<li class ='gallery-item'>
    <a href="${t}" class="gallery-link">
      <img class ="gallery-img" src="${o}" alt="${l}" />
      <div class="image-info">
        <span>Likes: ${e}</span>
        <span>Views: ${s}</span>
        <span>Comments: ${a}</span>
        <span>Downloads: ${E}</span>
      </div>
  </a>
</li>`).join(""),n=document.querySelector(".gallery"),v=document.querySelector(".js-search-form"),u=document.querySelector(".loader"),i=document.querySelector(".button");let c="",d=1,h=0,L=new w(".gallery a",{captionsData:"alt",captionDelay:250});async function M(r){if(r.preventDefault(),c=r.target.elements.searchKeywords.value.trim(),i.classList.add("d-none"),c===""){n.innerHTML="",r.target.reset(),m.show({message:"Input field can not be empty",position:"topRight",timeout:2e3,color:"red"});return}n.innerHTML="",u.classList.remove("is-hidden");try{const{data:t}=await g(c,d);if(t.total===0){m.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"red"});return}n.innerHTML=y(t.hits),h=Math.ceil(t.totalHits/f),h>1&&i.classList.remove("d-none"),L.refresh()}catch(t){console.log(t)}r.target.reset(),u.classList.add("is-hidden")}const q=()=>{const t=n.querySelector("li.gallery-item:last-child").getBoundingClientRect().height;window.scrollBy(0,t*3)};async function b(){d+=1,u.classList.remove("is-hidden");try{const{data:r}=await g(c,d);n.insertAdjacentHTML("beforeend",y(r.hits)),u.classList.add("is-hidden"),q(),d>h&&(i.classList.add("d-none"),i.removeEventListener("click",b),m.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"blue"})),L.refresh()}catch(r){console.log(r)}}v.addEventListener("submit",M);i.addEventListener("click",b);
//# sourceMappingURL=index.js.map
